config/routes.rb
Rails.application.routes.draw do
  namespace :glossary do
    resources :topics, only: [:index, :show] do
      resources :terms, only: [:show]
    end
    get 'topics/index'
    root 'topics#index'
  end
  get 'welcome/index'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  attribute :name, :string
  has_many :terms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/glossary/terms_controller.rb
class Glossary::TermsController < ApplicationController
  def show
    @term = Term.find(params[:id])
  end
end

app/controllers/glossary/topics_controller.rb
class Glossary::TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end
  
  def show
    @topic = Topic.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_glossary_namespace?
    controller.class.parent.to_s.downcase == 'glossary'
  end
end

app/helpers/glossary/terms_helper.rb
module Glossary::TermsHelper
end

app/helpers/glossary/topics_helper.rb
module Glossary::TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/glossary/terms/show.html.erb
<nav aria-label="breadcrumb">  
  <ol class="breadcrumb">  
    <li class="breadcrumb-item"><%= link_to 'Inicio', root_path %></li>  
    <li class="breadcrumb-item"><%= link_to 'Glosario', glossary_root_path %></li>  
    <li class="breadcrumb-item"><%= link_to @term.topic.name, glossary_topic_path(@term.topic) %></li>  
    <li class="breadcrumb-item active"><%= @term.name %></li>  
  </ol>  
</nav>
<div class="row">
  <div class="col-md-3 col-xl-2 border-right">
    <nav class="nav nav-pills flex-column">
      <% @term.topic.terms.each do |t| %>
        <%= link_to t.name, glossary_topic_term_path(t.topic, t), class: t == @term ? 'nav-link active' : 'nav-link' %>
      <% end %>
    </nav>
  </div>
  <main class="col-md-9 col-xl-10 pl-md-5">
    <h1 class="display-4"><%= @term.name %></h1>
  </main>
</div>

app/views/glossary/topics/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Inicio', root_path %></li>
    <li class="breadcrumb-item active">Glosario</li>
  </ol>
</nav>
<h1 class="display-4">Glosario</h1>
<div class="card-columns">
  <% @topics.each do |topic| %>
    <div class="card">
      <div class="card-body">
        <h2 class="card-title"><%= topic.name %></h2>
        <%= link_to 'Ver detalles', glossary_topic_path(topic), class: 'card-link' %>
      </div>
    </div>
  <% end %>
</div>

app/views/glossary/topics/show.html.erb
<nav aria-label="breadcrumb"> 
  <ol class="breadcrumb"> 
    <li class="breadcrumb-item"><%= link_to 'Inicio', root_path %></li> 
    <li class="breadcrumb-item"><%= link_to 'Glosario', glossary_root_path %></li> 
    <li class="breadcrumb-item active"><%= @topic.name %></li> 
  </ol> 
</nav>
<div class="row">
  <div class="col-md-3 col-xl-2 border-right">
    <nav class="nav flex-column">
      <% @topic.terms.each do |term| %>
        <%= link_to term.name, glossary_topic_term_path(@topic, term), class: 'nav-link' %>
      <% end %>
    </nav>
  </div>
  <main class="col-md-9 col-xl-10 pl-md-5">
    <h1 class="display-4"><%= @topic.name %></h1>
  </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GlosarioLsu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm border-bottom mb-3">
      <%= link_to 'Nombre', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Glosario', glossary_root_path, class: is_glossary_namespace?? 'nav-link active': 'nav-link' %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Blog</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Bienvenide</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <%= video_tag 'flower.mp4', controls: true, class: 'embed-responsive' %>
</div>_